---
title: Tal McThenia
url: https://spudfish.github.io
baseurl: "/hydejack-20251028"
lang: en
description: "Read recent writing projects, find out about Tal McThenia, contact him or his literary agent from this one page portfolio site."
tagline: writer
logo: "/assets/img/logo.png"
author: author1
menu:
- title: Work
  url: "#work"
- title: Bio
  url: "#bio"
- title: Contact
  url: "#contact"
copyright: "Â© 2025. All rights reserved."
theme: jekyll-theme-hydejack
accent_image: "/assets/img/sidebar-bg.jpg"
accent_color: rgb(144,176,200)
theme_color: rgb(48,95,135)
google_fonts: "Noticia+Text:ital,wght@0,400;0,700;1,400;1,700&family=Open+Sans:wdth,wght@87.5,300..800&display=swap"
font:                  Open Sans, Helvetica, Arial, sans-serif
font_heading:          Noticia Text, Open Sans, Helvetica, Arial, sans-serif
defaults:
- scope:
    path: assets/
  values:
    sitemap: false
- scope:
    path: ''
    type: projects
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_categories
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_tags
  values:
    seo:
      type: WebPage
hydejack:
  post_addons: []
  project_addons: []
  no_mark_external: true
  no_push_state: false
  no_drawer: false
  no_navbar: false
  no_search: true
  no_inline_css: true
  no_page_style: true
  no_break_layout: true
  no_toc: true
  no_third_column: true
  no_large_headings: true
  no_structured_data: true
  no_theme_color: false
  no_breadcrumbs: false
  use_lsi: false
  cookies_banner: false
  advertise: false
  hide_dates: false
  hide_last_modified: false
  dark_mode:
    always: false
    dynamic: true
    icon: true
  offline:
    enabled: false
    cache_version: 13
    precache_assets:
    - "/assets/img/swipe.svg"
collections:
  other-work:
    title: Other Work
    output: false
  top-work:
    title: Top Work
    output: false
exclude:
- ".jekyll-cache"
- ".sass-cache"
- ".ruby-lsp"
- ".wrangler"
- "*.toml"
- vendor
- Gemfile
- Gemfile.lock
- functions
- "*-unused.md"
include:
- _routes.json
- ".well-known"
- LICENSE.md
plugins:
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
optional_front_matter:
  remove_originals: true
readme_index:
  enabled: false
  remove_originals: false
  with_frontmatter: false
relative_links:
  collections: true
titles_from_headings:
  strip_title: true
  collections: true
compress_html:
  comments:
  - "<!--"
  - "-->"
  clippings: all
  endings: all
  ignore:
    envs:
    - development
sass:
  style: compressed
